// Jenkinsfile for Node.js pipeline

pipeline {
  agent any

  tools {
    nodejs "NodeJS 16"
  }

  stages {
    stage('Install') {
      steps {
        sh 'npm install'
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
  }
}
